<?php

namespace Database\Seeders\PokemonSleep;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;

class ChoicePokemonConstrainedSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('choice_pokemon_constraineds')->insert([
            ['id'=>1, 'name'=>'フシギダネ', 'image_path'=>'images/1.png', 'create_pokemon_template_id'=>1, 'create_pokemon_template2_id'=>1,  'create_pokemon_template3_id'=>1, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>2, 'name'=>'フシギソウ', 'image_path'=>'images/2.png', 'create_pokemon_template_id'=>2, 'create_pokemon_template2_id'=>2,  'create_pokemon_template3_id'=>2, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>3, 'name'=>'フシギバナ', 'image_path'=>'images/3.png', 'create_pokemon_template_id'=>3, 'create_pokemon_template2_id'=>3,  'create_pokemon_template3_id'=>3, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>4, 'name'=>'ヒトカゲ', 'image_path'=>'images/4.png', 'create_pokemon_template_id'=>4, 'create_pokemon_template2_id'=>4,  'create_pokemon_template3_id'=>4, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>5, 'name'=>'リザード', 'image_path'=>'images/5.png', 'create_pokemon_template_id'=>5, 'create_pokemon_template2_id'=>5,  'create_pokemon_template3_id'=>5, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>6, 'name'=>'リザードン', 'image_path'=>'images/6.png', 'create_pokemon_template_id'=>6, 'create_pokemon_template2_id'=>6,  'create_pokemon_template3_id'=>6, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>7, 'name'=>'ゼニガメ', 'image_path'=>'images/7.png', 'create_pokemon_template_id'=>7, 'create_pokemon_template2_id'=>7,  'create_pokemon_template3_id'=>7, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>8, 'name'=>'カメール', 'image_path'=>'images/8.png', 'create_pokemon_template_id'=>8, 'create_pokemon_template2_id'=>8,  'create_pokemon_template3_id'=>8, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>9, 'name'=>'カメックス', 'image_path'=>'images/9.png', 'create_pokemon_template_id'=>9, 'create_pokemon_template2_id'=>9,  'create_pokemon_template3_id'=>9, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>10, 'name'=>'キャタピー', 'image_path'=>'images/10.png', 'create_pokemon_template_id'=>10, 'create_pokemon_template2_id'=>10,  'create_pokemon_template3_id'=>10, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>11, 'name'=>'トランセル', 'image_path'=>'images/11.png', 'create_pokemon_template_id'=>11, 'create_pokemon_template2_id'=>11,  'create_pokemon_template3_id'=>11, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>12, 'name'=>'バタフリー', 'image_path'=>'images/12.png', 'create_pokemon_template_id'=>12, 'create_pokemon_template2_id'=>12,  'create_pokemon_template3_id'=>12, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>19, 'name'=>'コラッタ', 'image_path'=>'images/19.png', 'create_pokemon_template_id'=>19, 'create_pokemon_template2_id'=>19,  'create_pokemon_template3_id'=>19, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>20, 'name'=>'ラッタ', 'image_path'=>'images/20.png', 'create_pokemon_template_id'=>20, 'create_pokemon_template2_id'=>20,  'create_pokemon_template3_id'=>20, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>23, 'name'=>'アーボ', 'image_path'=>'images/23.png', 'create_pokemon_template_id'=>23, 'create_pokemon_template2_id'=>23,  'create_pokemon_template3_id'=>23, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>24, 'name'=>'アーボック', 'image_path'=>'images/24.png', 'create_pokemon_template_id'=>24, 'create_pokemon_template2_id'=>24,  'create_pokemon_template3_id'=>24, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>25, 'name'=>'ピカチュウ', 'image_path'=>'images/25.png', 'create_pokemon_template_id'=>25, 'create_pokemon_template2_id'=>25, 'create_pokemon_template3_id'=>25, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>26, 'name'=>'ライチュウ', 'image_path'=>'images/26.png', 'create_pokemon_template_id'=>26, 'create_pokemon_template2_id'=>26, 'create_pokemon_template3_id'=>26, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>35, 'name'=>'ピッピ', 'image_path'=>'images/35.png', 'create_pokemon_template_id'=>35, 'create_pokemon_template2_id'=>35, 'create_pokemon_template3_id'=>35, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>36, 'name'=>'ピクシー', 'image_path'=>'images/36.png', 'create_pokemon_template_id'=>36, 'create_pokemon_template2_id'=>36, 'create_pokemon_template3_id'=>36, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>37, 'name'=>'ロコン', 'image_path'=>'images/37.png', 'create_pokemon_template_id'=>37, 'create_pokemon_template2_id'=>37, 'create_pokemon_template3_id'=>37, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>38, 'name'=>'キュウコン', 'image_path'=>'images/38.png', 'create_pokemon_template_id'=>38, 'create_pokemon_template2_id'=>38, 'create_pokemon_template3_id'=>38, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>39, 'name'=>'プリン', 'image_path'=>'images/39.png', 'create_pokemon_template_id'=>39, 'create_pokemon_template2_id'=>39, 'create_pokemon_template3_id'=>39, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>40, 'name'=>'プクリン', 'image_path'=>'images/40.png', 'create_pokemon_template_id'=>40, 'create_pokemon_template2_id'=>40, 'create_pokemon_template3_id'=>40, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>50, 'name'=>'ディグダ', 'image_path'=>'images/50.png', 'create_pokemon_template_id'=>50, 'create_pokemon_template2_id'=>50, 'create_pokemon_template3_id'=>50, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>51, 'name'=>'ダグトリオ', 'image_path'=>'images/51.png', 'create_pokemon_template_id'=>51, 'create_pokemon_template2_id'=>51, 'create_pokemon_template3_id'=>51, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>52, 'name'=>'ニャース', 'image_path'=>'images/52.png', 'create_pokemon_template_id'=>52, 'create_pokemon_template2_id'=>52, 'create_pokemon_template3_id'=>52, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>53, 'name'=>'ペルシアン', 'image_path'=>'images/53.png', 'create_pokemon_template_id'=>53, 'create_pokemon_template2_id'=>53, 'create_pokemon_template3_id'=>53, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>54, 'name'=>'コダック', 'image_path'=>'images/54.png', 'create_pokemon_template_id'=>54, 'create_pokemon_template2_id'=>54, 'create_pokemon_template3_id'=>54, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>55, 'name'=>'ゴルダック', 'image_path'=>'images/55.png', 'create_pokemon_template_id'=>55, 'create_pokemon_template2_id'=>55, 'create_pokemon_template3_id'=>55, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>56, 'name'=>'マンキー', 'image_path'=>'images/56.png', 'create_pokemon_template_id'=>56, 'create_pokemon_template2_id'=>56, 'create_pokemon_template3_id'=>56, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>57, 'name'=>'オコリザル', 'image_path'=>'images/57.png', 'create_pokemon_template_id'=>57, 'create_pokemon_template2_id'=>57, 'create_pokemon_template3_id'=>57, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>58, 'name'=>'ガーディ', 'image_path'=>'images/58.png', 'create_pokemon_template_id'=>58, 'create_pokemon_template2_id'=>58, 'create_pokemon_template3_id'=>58, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>59, 'name'=>'ウインディ', 'image_path'=>'images/59.png', 'create_pokemon_template_id'=>59, 'create_pokemon_template2_id'=>59, 'create_pokemon_template3_id'=>59, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>69, 'name'=>'マダツボミ', 'image_path'=>'images/69.png', 'create_pokemon_template_id'=>69, 'create_pokemon_template2_id'=>69, 'create_pokemon_template3_id'=>69, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>70, 'name'=>'ウツドン', 'image_path'=>'images/70.png', 'create_pokemon_template_id'=>70, 'create_pokemon_template2_id'=>70, 'create_pokemon_template3_id'=>70, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>71, 'name'=>'ウツボット', 'image_path'=>'images/71.png', 'create_pokemon_template_id'=>71, 'create_pokemon_template2_id'=>71, 'create_pokemon_template3_id'=>71, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>74, 'name'=>'イシツブテ', 'image_path'=>'images/74.png', 'create_pokemon_template_id'=>74, 'create_pokemon_template2_id'=>74, 'create_pokemon_template3_id'=>74, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>75, 'name'=>'ゴローン', 'image_path'=>'images/75.png', 'create_pokemon_template_id'=>75, 'create_pokemon_template2_id'=>75, 'create_pokemon_template3_id'=>75, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>76, 'name'=>'ゴローニャ', 'image_path'=>'images/76.png', 'create_pokemon_template_id'=>76, 'create_pokemon_template2_id'=>76, 'create_pokemon_template3_id'=>76, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>79, 'name'=>'ヤドン', 'image_path'=>'images/79.png', 'create_pokemon_template_id'=>79, 'create_pokemon_template2_id'=>79, 'create_pokemon_template3_id'=>79, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>80, 'name'=>'ヤドラン', 'image_path'=>'images/80.png', 'create_pokemon_template_id'=>80, 'create_pokemon_template2_id'=>80, 'create_pokemon_template3_id'=>80, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>81, 'name'=>'コイル', 'image_path'=>'images/81.png', 'create_pokemon_template_id'=>81, 'create_pokemon_template2_id'=>81, 'create_pokemon_template3_id'=>81, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>82, 'name'=>'レアコイル', 'image_path'=>'images/82.png', 'create_pokemon_template_id'=>82, 'create_pokemon_template2_id'=>82, 'create_pokemon_template3_id'=>82, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>84, 'name'=>'ドードー', 'image_path'=>'images/84.png', 'create_pokemon_template_id'=>84, 'create_pokemon_template2_id'=>84, 'create_pokemon_template3_id'=>84, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>85, 'name'=>'ドードリオ', 'image_path'=>'images/85.png', 'create_pokemon_template_id'=>85, 'create_pokemon_template2_id'=>85, 'create_pokemon_template3_id'=>85, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>92, 'name'=>'ゴース', 'image_path'=>'images/92.png', 'create_pokemon_template_id'=>92, 'create_pokemon_template2_id'=>92, 'create_pokemon_template3_id'=>92, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>93, 'name'=>'ゴースト', 'image_path'=>'images/93.png', 'create_pokemon_template_id'=>93, 'create_pokemon_template2_id'=>93, 'create_pokemon_template3_id'=>93, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>94, 'name'=>'ゲンガー', 'image_path'=>'images/94.png', 'create_pokemon_template_id'=>94, 'create_pokemon_template2_id'=>94, 'create_pokemon_template3_id'=>94, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>95, 'name'=>'イワーク', 'image_path'=>'images/95.png', 'create_pokemon_template_id'=>95, 'create_pokemon_template2_id'=>95, 'create_pokemon_template3_id'=>95, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>104, 'name'=>'カラカラ', 'image_path'=>'images/104.png', 'create_pokemon_template_id'=>104, 'create_pokemon_template2_id'=>104, 'create_pokemon_template3_id'=>104, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>105, 'name'=>'ガラガラ', 'image_path'=>'images/105.png', 'create_pokemon_template_id'=>105, 'create_pokemon_template2_id'=>105, 'create_pokemon_template3_id'=>105, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>115, 'name'=>'ガルーラ', 'image_path'=>'images/115.png', 'create_pokemon_template_id'=>115, 'create_pokemon_template2_id'=>115, 'create_pokemon_template3_id'=>115, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>122, 'name'=>'バリヤード', 'image_path'=>'images/122.png', 'create_pokemon_template_id'=>122, 'create_pokemon_template2_id'=>122, 'create_pokemon_template3_id'=>122, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>127, 'name'=>'カイロス', 'image_path'=>'images/127.png', 'create_pokemon_template_id'=>127, 'create_pokemon_template2_id'=>127, 'create_pokemon_template3_id'=>127, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>132, 'name'=>'メタモン', 'image_path'=>'images/132.png', 'create_pokemon_template_id'=>132, 'create_pokemon_template2_id'=>132, 'create_pokemon_template3_id'=>132, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>133, 'name'=>'イーブイ', 'image_path'=>'images/133.png', 'create_pokemon_template_id'=>133, 'create_pokemon_template2_id'=>133,  'create_pokemon_template3_id'=>133, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>134, 'name'=>'シャワーズ', 'image_path'=>'images/134.png', 'create_pokemon_template_id'=>134, 'create_pokemon_template2_id'=>134, 'create_pokemon_template3_id'=>134, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>135, 'name'=>'サンダース', 'image_path'=>'images/135.png', 'create_pokemon_template_id'=>135, 'create_pokemon_template2_id'=>135, 'create_pokemon_template3_id'=>135, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>136, 'name'=>'ブースター', 'image_path'=>'images/136.png', 'create_pokemon_template_id'=>136, 'create_pokemon_template2_id'=>136, 'create_pokemon_template3_id'=>136, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>147, 'name'=>'ミニリュウ', 'image_path'=>'images/147.png', 'create_pokemon_template_id'=>147, 'create_pokemon_template2_id'=>147, 'create_pokemon_template3_id'=>147, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>148, 'name'=>'ハクリュー', 'image_path'=>'images/148.png', 'create_pokemon_template_id'=>148, 'create_pokemon_template2_id'=>148, 'create_pokemon_template3_id'=>148, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>149, 'name'=>'カイリュー', 'image_path'=>'images/149.png', 'create_pokemon_template_id'=>149, 'create_pokemon_template2_id'=>149, 'create_pokemon_template3_id'=>149, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>152, 'name'=>'チコリータ', 'image_path'=>'images/152.png', 'create_pokemon_template_id'=>152, 'create_pokemon_template2_id'=>152, 'create_pokemon_template3_id'=>152, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>153, 'name'=>'ベイリーフ', 'image_path'=>'images/153.png', 'create_pokemon_template_id'=>153, 'create_pokemon_template2_id'=>153, 'create_pokemon_template3_id'=>153, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>154, 'name'=>'メガニウム', 'image_path'=>'images/154.png', 'create_pokemon_template_id'=>154, 'create_pokemon_template2_id'=>154, 'create_pokemon_template3_id'=>154, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>155, 'name'=>'ヒノアラシ', 'image_path'=>'images/155.png', 'create_pokemon_template_id'=>155, 'create_pokemon_template2_id'=>155, 'create_pokemon_template3_id'=>155, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>156, 'name'=>'マグマラシ', 'image_path'=>'images/156.png', 'create_pokemon_template_id'=>156, 'create_pokemon_template2_id'=>156, 'create_pokemon_template3_id'=>156, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>157, 'name'=>'バクフーン', 'image_path'=>'images/157.png', 'create_pokemon_template_id'=>157, 'create_pokemon_template2_id'=>157, 'create_pokemon_template3_id'=>157, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>158, 'name'=>'ワニノコ', 'image_path'=>'images/158.png', 'create_pokemon_template_id'=>158, 'create_pokemon_template2_id'=>158, 'create_pokemon_template3_id'=>158, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>159, 'name'=>'アリゲイツ', 'image_path'=>'images/159.png', 'create_pokemon_template_id'=>159, 'create_pokemon_template2_id'=>159, 'create_pokemon_template3_id'=>159, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>160, 'name'=>'オーダイル', 'image_path'=>'images/160.png', 'create_pokemon_template_id'=>160, 'create_pokemon_template2_id'=>160, 'create_pokemon_template3_id'=>160, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>172, 'name'=>'ピチュー', 'image_path'=>'images/172.png', 'create_pokemon_template_id'=>172, 'create_pokemon_template2_id'=>172, 'create_pokemon_template3_id'=>172, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>173, 'name'=>'ピィ', 'image_path'=>'images/173.png', 'create_pokemon_template_id'=>173, 'create_pokemon_template2_id'=>173, 'create_pokemon_template3_id'=>173, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>174, 'name'=>'ププリン', 'image_path'=>'images/174.png', 'create_pokemon_template_id'=>174, 'create_pokemon_template2_id'=>174, 'create_pokemon_template3_id'=>174, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>175, 'name'=>'トゲピー', 'image_path'=>'images/175.png', 'create_pokemon_template_id'=>175, 'create_pokemon_template2_id'=>175, 'create_pokemon_template3_id'=>175, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>176, 'name'=>'トゲチック', 'image_path'=>'images/176.png', 'create_pokemon_template_id'=>176, 'create_pokemon_template2_id'=>176, 'create_pokemon_template3_id'=>176, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>179, 'name'=>'メリープ', 'image_path'=>'images/179.png', 'create_pokemon_template_id'=>179, 'create_pokemon_template2_id'=>179, 'create_pokemon_template3_id'=>179, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>180, 'name'=>'モココ', 'image_path'=>'images/180.png', 'create_pokemon_template_id'=>180, 'create_pokemon_template2_id'=>180, 'create_pokemon_template3_id'=>180, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>181, 'name'=>'デンリュウ', 'image_path'=>'images/181.png', 'create_pokemon_template_id'=>181, 'create_pokemon_template2_id'=>181, 'create_pokemon_template3_id'=>181, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>185, 'name'=>'ウソッキー', 'image_path'=>'images/185.png', 'create_pokemon_template_id'=>185, 'create_pokemon_template2_id'=>185, 'create_pokemon_template3_id'=>185, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>194, 'name'=>'ウパー', 'image_path'=>'images/194.png', 'create_pokemon_template_id'=>194, 'create_pokemon_template2_id'=>194, 'create_pokemon_template3_id'=>194, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>195, 'name'=>'ヌオー', 'image_path'=>'images/195.png', 'create_pokemon_template_id'=>195, 'create_pokemon_template2_id'=>195, 'create_pokemon_template3_id'=>195, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>196, 'name'=>'エーフィ', 'image_path'=>'images/196.png', 'create_pokemon_template_id'=>196, 'create_pokemon_template2_id'=>196, 'create_pokemon_template3_id'=>196, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>197, 'name'=>'ブラッキー', 'image_path'=>'images/197.png', 'create_pokemon_template_id'=>197, 'create_pokemon_template2_id'=>197, 'create_pokemon_template3_id'=>197, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>199, 'name'=>'ヤドキング', 'image_path'=>'images/199.png', 'create_pokemon_template_id'=>199, 'create_pokemon_template2_id'=>199, 'create_pokemon_template3_id'=>199, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>202, 'name'=>'ソーナンス', 'image_path'=>'images/202.png', 'create_pokemon_template_id'=>202, 'create_pokemon_template2_id'=>202, 'create_pokemon_template3_id'=>202, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>208, 'name'=>'ハガネール', 'image_path'=>'images/208.png', 'create_pokemon_template_id'=>208, 'create_pokemon_template2_id'=>208, 'create_pokemon_template3_id'=>208, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>214, 'name'=>'ヘラクロス', 'image_path'=>'images/214.png', 'create_pokemon_template_id'=>214, 'create_pokemon_template2_id'=>214, 'create_pokemon_template3_id'=>214, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>225, 'name'=>'デリバード', 'image_path'=>'images/225.png', 'create_pokemon_template_id'=>225, 'create_pokemon_template2_id'=>225, 'create_pokemon_template3_id'=>225, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>228, 'name'=>'デルビル', 'image_path'=>'images/228.png', 'create_pokemon_template_id'=>228, 'create_pokemon_template2_id'=>228, 'create_pokemon_template3_id'=>228, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>229, 'name'=>'ヘルガー', 'image_path'=>'images/229.png', 'create_pokemon_template_id'=>229, 'create_pokemon_template2_id'=>229, 'create_pokemon_template3_id'=>229, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>243, 'name'=>'ライコウ', 'image_path'=>'images/243.png', 'create_pokemon_template_id'=>243, 'create_pokemon_template2_id'=>243, 'create_pokemon_template3_id'=>243, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>244, 'name'=>'エンテイ', 'image_path'=>'images/244.png', 'create_pokemon_template_id'=>244, 'create_pokemon_template2_id'=>244, 'create_pokemon_template3_id'=>244, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>245, 'name'=>'スイクン', 'image_path'=>'images/245.png', 'create_pokemon_template_id'=>245, 'create_pokemon_template2_id'=>245, 'create_pokemon_template3_id'=>245, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>246, 'name'=>'ヨーギラス', 'image_path'=>'images/246.png', 'create_pokemon_template_id'=>246, 'create_pokemon_template2_id'=>246, 'create_pokemon_template3_id'=>246, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>247, 'name'=>'サナギラス', 'image_path'=>'images/247.png', 'create_pokemon_template_id'=>247, 'create_pokemon_template2_id'=>247, 'create_pokemon_template3_id'=>247, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>248, 'name'=>'バンギラス', 'image_path'=>'images/248.png', 'create_pokemon_template_id'=>248, 'create_pokemon_template2_id'=>248, 'create_pokemon_template3_id'=>248, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>280, 'name'=>'ラルトス', 'image_path'=>'images/280.png', 'create_pokemon_template_id'=>280, 'create_pokemon_template2_id'=>280, 'create_pokemon_template3_id'=>280, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>281, 'name'=>'キルリア', 'image_path'=>'images/281.png', 'create_pokemon_template_id'=>281, 'create_pokemon_template2_id'=>281, 'create_pokemon_template3_id'=>281, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>282, 'name'=>'サーナイト', 'image_path'=>'images/282.png', 'create_pokemon_template_id'=>282, 'create_pokemon_template2_id'=>282, 'create_pokemon_template3_id'=>282, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>287, 'name'=>'ナマケロ', 'image_path'=>'images/287.png', 'create_pokemon_template_id'=>287, 'create_pokemon_template2_id'=>287, 'create_pokemon_template3_id'=>287, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>288, 'name'=>'ヤルキモノ', 'image_path'=>'images/288.png', 'create_pokemon_template_id'=>288, 'create_pokemon_template2_id'=>288, 'create_pokemon_template3_id'=>288, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>289, 'name'=>'ケッキング', 'image_path'=>'images/289.png', 'create_pokemon_template_id'=>289, 'create_pokemon_template2_id'=>289, 'create_pokemon_template3_id'=>289, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>302, 'name'=>'ヤミラミ', 'image_path'=>'images/302.png', 'create_pokemon_template_id'=>302, 'create_pokemon_template2_id'=>302, 'create_pokemon_template3_id'=>302, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>304, 'name'=>'ココドラ', 'image_path'=>'images/304.png', 'create_pokemon_template_id'=>304, 'create_pokemon_template2_id'=>304, 'create_pokemon_template3_id'=>304, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>305, 'name'=>'コドラ', 'image_path'=>'images/305.png', 'create_pokemon_template_id'=>305, 'create_pokemon_template2_id'=>305, 'create_pokemon_template3_id'=>305, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>306, 'name'=>'ボスコドラ', 'image_path'=>'images/306.png', 'create_pokemon_template_id'=>306, 'create_pokemon_template2_id'=>306, 'create_pokemon_template3_id'=>306, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>316, 'name'=>'ゴクリン', 'image_path'=>'images/316.png', 'create_pokemon_template_id'=>316, 'create_pokemon_template2_id'=>316, 'create_pokemon_template3_id'=>316, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>317, 'name'=>'マルノーム', 'image_path'=>'images/317.png', 'create_pokemon_template_id'=>317, 'create_pokemon_template2_id'=>317, 'create_pokemon_template3_id'=>317, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>333, 'name'=>'チルット', 'image_path'=>'images/333.png', 'create_pokemon_template_id'=>333, 'create_pokemon_template2_id'=>333, 'create_pokemon_template3_id'=>333, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>334, 'name'=>'チルタリス', 'image_path'=>'images/334.png', 'create_pokemon_template_id'=>334, 'create_pokemon_template2_id'=>334, 'create_pokemon_template3_id'=>334, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>353, 'name'=>'カゲボウズ', 'image_path'=>'images/353.png', 'create_pokemon_template_id'=>353, 'create_pokemon_template2_id'=>353, 'create_pokemon_template3_id'=>353, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>354, 'name'=>'ジュベッタ', 'image_path'=>'images/354.png', 'create_pokemon_template_id'=>354, 'create_pokemon_template2_id'=>354, 'create_pokemon_template3_id'=>354, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>359, 'name'=>'アブソル', 'image_path'=>'images/359.png', 'create_pokemon_template_id'=>359, 'create_pokemon_template2_id'=>359, 'create_pokemon_template3_id'=>359, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>360, 'name'=>'ソーナノ', 'image_path'=>'images/360.png', 'create_pokemon_template_id'=>360, 'create_pokemon_template2_id'=>360, 'create_pokemon_template3_id'=>360, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>363, 'name'=>'タマザラシ', 'image_path'=>'images/363.png', 'create_pokemon_template_id'=>363, 'create_pokemon_template2_id'=>363, 'create_pokemon_template3_id'=>363, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>364, 'name'=>'トドグラー', 'image_path'=>'images/364.png', 'create_pokemon_template_id'=>364, 'create_pokemon_template2_id'=>364, 'create_pokemon_template3_id'=>364, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>365, 'name'=>'トドゼルガ', 'image_path'=>'images/365.png', 'create_pokemon_template_id'=>365, 'create_pokemon_template2_id'=>365, 'create_pokemon_template3_id'=>365, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>403, 'name'=>'コリンク', 'image_path'=>'images/403.png', 'create_pokemon_template_id'=>403, 'create_pokemon_template2_id'=>403, 'create_pokemon_template3_id'=>403, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>404, 'name'=>'ルクシオ', 'image_path'=>'images/404.png', 'create_pokemon_template_id'=>404, 'create_pokemon_template2_id'=>404, 'create_pokemon_template3_id'=>404, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>405, 'name'=>'レントラー', 'image_path'=>'images/405.png', 'create_pokemon_template_id'=>405, 'create_pokemon_template2_id'=>405, 'create_pokemon_template3_id'=>405, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>438, 'name'=>'ウソハチ', 'image_path'=>'images/438.png', 'create_pokemon_template_id'=>438, 'create_pokemon_template2_id'=>438, 'create_pokemon_template3_id'=>438, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>439, 'name'=>'マネネ', 'image_path'=>'images/439.png', 'create_pokemon_template_id'=>439, 'create_pokemon_template2_id'=>439, 'create_pokemon_template3_id'=>439, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>447, 'name'=>'リオル', 'image_path'=>'images/447.png', 'create_pokemon_template_id'=>447, 'create_pokemon_template2_id'=>447, 'create_pokemon_template3_id'=>447, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>448, 'name'=>'ルカリオ', 'image_path'=>'images/448.png', 'create_pokemon_template_id'=>448, 'create_pokemon_template2_id'=>448, 'create_pokemon_template3_id'=>448, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>453, 'name'=>'グレッグル', 'image_path'=>'images/453.png', 'create_pokemon_template_id'=>453, 'create_pokemon_template2_id'=>453, 'create_pokemon_template3_id'=>453, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>454, 'name'=>'ドクロッグ', 'image_path'=>'images/454.png', 'create_pokemon_template_id'=>454, 'create_pokemon_template2_id'=>454, 'create_pokemon_template3_id'=>454, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>459, 'name'=>'ユキカブリ', 'image_path'=>'images/459.png', 'create_pokemon_template_id'=>459, 'create_pokemon_template2_id'=>459, 'create_pokemon_template3_id'=>459, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>460, 'name'=>'ユキノオー', 'image_path'=>'images/460.png', 'create_pokemon_template_id'=>460, 'create_pokemon_template2_id'=>460, 'create_pokemon_template3_id'=>460, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>462, 'name'=>'ジバコイル', 'image_path'=>'images/462.png', 'create_pokemon_template_id'=>462, 'create_pokemon_template2_id'=>462, 'create_pokemon_template3_id'=>462, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>468, 'name'=>'トゲキッス', 'image_path'=>'images/468.png', 'create_pokemon_template_id'=>468, 'create_pokemon_template2_id'=>468, 'create_pokemon_template3_id'=>468, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>470, 'name'=>'リーフィア', 'image_path'=>'images/470.png', 'create_pokemon_template_id'=>470, 'create_pokemon_template2_id'=>470, 'create_pokemon_template3_id'=>470, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>471, 'name'=>'グレイシア', 'image_path'=>'images/471.png', 'create_pokemon_template_id'=>471, 'create_pokemon_template2_id'=>471, 'create_pokemon_template3_id'=>471, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>475, 'name'=>'エルレイド', 'image_path'=>'images/475.png', 'create_pokemon_template_id'=>475, 'create_pokemon_template2_id'=>475, 'create_pokemon_template3_id'=>475, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>700, 'name'=>'ニンフィア', 'image_path'=>'images/700.png', 'create_pokemon_template_id'=>700, 'create_pokemon_template2_id'=>700, 'create_pokemon_template3_id'=>700, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>702, 'name'=>'デデンネ', 'image_path'=>'images/702.png', 'create_pokemon_template_id'=>702, 'create_pokemon_template2_id'=>702, 'create_pokemon_template3_id'=>702, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>736, 'name'=>'アゴジムシ', 'image_path'=>'images/736.png', 'create_pokemon_template_id'=>736, 'create_pokemon_template2_id'=>736, 'create_pokemon_template3_id'=>736, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>737, 'name'=>'デンヂムシ', 'image_path'=>'images/737.png', 'create_pokemon_template_id'=>737, 'create_pokemon_template2_id'=>737, 'create_pokemon_template3_id'=>737, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>738, 'name'=>'クワガノン', 'image_path'=>'images/738.png', 'create_pokemon_template_id'=>738, 'create_pokemon_template2_id'=>738, 'create_pokemon_template3_id'=>738, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>759, 'name'=>'ヌイコグマ', 'image_path'=>'images/759.png', 'create_pokemon_template_id'=>759, 'create_pokemon_template2_id'=>759, 'create_pokemon_template3_id'=>759, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>760, 'name'=>'キテルグマ', 'image_path'=>'images/760.png', 'create_pokemon_template_id'=>760, 'create_pokemon_template2_id'=>760, 'create_pokemon_template3_id'=>760, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>764, 'name'=>'キュワワー', 'image_path'=>'images/764.png', 'create_pokemon_template_id'=>764, 'create_pokemon_template2_id'=>764, 'create_pokemon_template3_id'=>764, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>845, 'name'=>'ウッウ', 'image_path'=>'images/845.png', 'create_pokemon_template_id'=>845, 'create_pokemon_template2_id'=>845, 'create_pokemon_template3_id'=>845, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>906, 'name'=>'ニャオハ', 'image_path'=>'images/906.png', 'create_pokemon_template_id'=>906, 'create_pokemon_template2_id'=>906, 'create_pokemon_template3_id'=>906, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>907, 'name'=>'ニャローテ', 'image_path'=>'images/907.png', 'create_pokemon_template_id'=>907, 'create_pokemon_template2_id'=>907, 'create_pokemon_template3_id'=>907, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>908, 'name'=>'マスカーニャ', 'image_path'=>'images/908.png', 'create_pokemon_template_id'=>908, 'create_pokemon_template2_id'=>908, 'create_pokemon_template3_id'=>908, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>909, 'name'=>'ホゲータ', 'image_path'=>'images/909.png', 'create_pokemon_template_id'=>909, 'create_pokemon_template2_id'=>909, 'create_pokemon_template3_id'=>909, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>910, 'name'=>'アチゲータ', 'image_path'=>'images/910.png', 'create_pokemon_template_id'=>910, 'create_pokemon_template2_id'=>910, 'create_pokemon_template3_id'=>910, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>911, 'name'=>'ラウドボーン', 'image_path'=>'images/911.png', 'create_pokemon_template_id'=>911, 'create_pokemon_template2_id'=>911, 'create_pokemon_template3_id'=>911, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>912, 'name'=>'クワッス', 'image_path'=>'images/912.png', 'create_pokemon_template_id'=>912, 'create_pokemon_template2_id'=>912, 'create_pokemon_template3_id'=>912, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>913, 'name'=>'ウェルカモ', 'image_path'=>'images/913.png', 'create_pokemon_template_id'=>913, 'create_pokemon_template2_id'=>913, 'create_pokemon_template3_id'=>913, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>914, 'name'=>'ウェーニバル', 'image_path'=>'images/914.png', 'create_pokemon_template_id'=>914, 'create_pokemon_template2_id'=>914, 'create_pokemon_template3_id'=>914, 'created_at'=>now(), 'updated_at'=>now()],
        ]);
    }
}
